# Generated by Django 6.1.1 on 2026-09-20 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_no', models.PositiveBigIntegerField(unique=True)),
                ('batch', models.PositiveBigIntegerField()),
                ('faculty', models.CharField(max_length=88)),
                ('address', models.CharField(max_length=255)),
                ('phoneNo', models.PositiveBigIntegerField(max_length=11)),
                ('isActive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
