# Generated by Django 6.1.1 on 2026-09-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.PositiveBigIntegerField(),
        ),
    ]
