# Generated by Django 6.1.1 on 2026-09-23 04:02

import storages.backends.s3
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to=student.models.media_storage_path),
        ),
    ]
