# Generated by Django 6.1.1 on 2026-09-23 05:07

import core.storage_backend
import student.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_no',
        ),
        migrations.AddField(
            model_name='student',
            name='symbolNo',
            field=models.PositiveIntegerField(default=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='batch',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phoneNo',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backend.mediaStorage, upload_to=student.models.media_storage_path),
        ),
    ]
